# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Relations.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grp1 = QtWidgets.QGroupBox(self.centralwidget)
        self.grp1.setGeometry(QtCore.QRect(20, 20, 301, 301))
        self.grp1.setTitle("")
        self.grp1.setObjectName("grp1")
        self.btnSubtract = QtWidgets.QPushButton(self.grp1)
        self.btnSubtract.setGeometry(QtCore.QRect(250, 140, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSubtract.setFont(font)
        self.btnSubtract.setObjectName("btnSubtract")
        self.btnAdd = QtWidgets.QPushButton(self.grp1)
        self.btnAdd.setGeometry(QtCore.QRect(10, 140, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.layoutWidget = QtWidgets.QWidget(self.grp1)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 20, 135, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txt1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt1.setFont(font)
        self.txt1.setAlignment(QtCore.Qt.AlignCenter)
        self.txt1.setObjectName("txt1")
        self.verticalLayout.addWidget(self.txt1)
        self.txt2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt2.setFont(font)
        self.txt2.setAlignment(QtCore.Qt.AlignCenter)
        self.txt2.setObjectName("txt2")
        self.verticalLayout.addWidget(self.txt2)
        self.txt3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt3.setFont(font)
        self.txt3.setAlignment(QtCore.Qt.AlignCenter)
        self.txt3.setObjectName("txt3")
        self.verticalLayout.addWidget(self.txt3)
        self.txt4 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt4.setFont(font)
        self.txt4.setAlignment(QtCore.Qt.AlignCenter)
        self.txt4.setObjectName("txt4")
        self.verticalLayout.addWidget(self.txt4)
        self.txt5 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt5.setFont(font)
        self.txt5.setAlignment(QtCore.Qt.AlignCenter)
        self.txt5.setObjectName("txt5")
        self.verticalLayout.addWidget(self.txt5)
        self.grp2 = QtWidgets.QGroupBox(self.centralwidget)
        self.grp2.setGeometry(QtCore.QRect(330, 20, 641, 301))
        self.grp2.setTitle("")
        self.grp2.setObjectName("grp2")
        self.lblToday = QtWidgets.QLabel(self.grp2)
        self.lblToday.setGeometry(QtCore.QRect(140, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblToday.setFont(font)
        self.lblToday.setAlignment(QtCore.Qt.AlignCenter)
        self.lblToday.setObjectName("lblToday")
        self.txtDay = QtWidgets.QLineEdit(self.grp2)
        self.txtDay.setGeometry(QtCore.QRect(420, 140, 133, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtDay.setFont(font)
        self.txtDay.setText("")
        self.txtDay.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDay.setObjectName("txtDay")
        self.layoutWidget1 = QtWidgets.QWidget(self.grp2)
        self.layoutWidget1.setGeometry(QtCore.QRect(280, 20, 112, 271))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnMon = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnMon.setFont(font)
        self.btnMon.setObjectName("btnMon")
        self.verticalLayout_2.addWidget(self.btnMon)
        self.btnTue = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnTue.setFont(font)
        self.btnTue.setObjectName("btnTue")
        self.verticalLayout_2.addWidget(self.btnTue)
        self.btnWed = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnWed.setFont(font)
        self.btnWed.setObjectName("btnWed")
        self.verticalLayout_2.addWidget(self.btnWed)
        self.btnThu = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnThu.setFont(font)
        self.btnThu.setObjectName("btnThu")
        self.verticalLayout_2.addWidget(self.btnThu)
        self.btnFri = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnFri.setFont(font)
        self.btnFri.setObjectName("btnFri")
        self.verticalLayout_2.addWidget(self.btnFri)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnAdd, self.txt1)
        MainWindow.setTabOrder(self.txt1, self.txt2)
        MainWindow.setTabOrder(self.txt2, self.txt3)
        MainWindow.setTabOrder(self.txt3, self.txt4)
        MainWindow.setTabOrder(self.txt4, self.txt5)
        MainWindow.setTabOrder(self.txt5, self.btnSubtract)
        MainWindow.setTabOrder(self.btnSubtract, self.btnMon)
        MainWindow.setTabOrder(self.btnMon, self.btnTue)
        MainWindow.setTabOrder(self.btnTue, self.btnWed)
        MainWindow.setTabOrder(self.btnWed, self.btnThu)
        MainWindow.setTabOrder(self.btnThu, self.btnFri)
        MainWindow.setTabOrder(self.btnFri, self.txtDay)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSubtract.setText(_translate("MainWindow", "-"))
        self.btnAdd.setText(_translate("MainWindow", "+"))
        self.txt1.setText(_translate("MainWindow", "3"))
        self.txt2.setText(_translate("MainWindow", "2"))
        self.txt3.setText(_translate("MainWindow", "7"))
        self.txt4.setText(_translate("MainWindow", "1"))
        self.txt5.setText(_translate("MainWindow", "5"))
        self.lblToday.setText(_translate("MainWindow", "Today is:"))
        self.btnMon.setText(_translate("MainWindow", "Monday"))
        self.btnTue.setText(_translate("MainWindow", "Tuesday"))
        self.btnWed.setText(_translate("MainWindow", "Wednesday"))
        self.btnThu.setText(_translate("MainWindow", "Thursday"))
        self.btnFri.setText(_translate("MainWindow", "Friday"))

